// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5kipvhrOgduttUfhabgHDTJefHZavy8',
    appId: '1:435245077591:android:050d4ca46255f2a1e27f12',
    messagingSenderId: '435245077591',
    projectId: 'users-ffe5e',
    storageBucket: 'users-ffe5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAiVQBS3lBUpYcHkMBV32LTC5mpekJnjg',
    appId: '1:435245077591:ios:867cf11a406454d4e27f12',
    messagingSenderId: '435245077591',
    projectId: 'users-ffe5e',
    storageBucket: 'users-ffe5e.appspot.com',
    androidClientId: '435245077591-t91jkqr1l308vacpqadddm09ehev8ij4.apps.googleusercontent.com',
    iosClientId: '435245077591-d0eilair0mn61gc6mhunceelqu5c99u9.apps.googleusercontent.com',
    iosBundleId: 'com.synamall.aswaqalhelal',
  );
}
