name: aswaqalhelal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  firebase_app_check: ^0.1.1+1
  intl: ^0.17.0 # Add this line  
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  json_serializable: ^6.1.4
  json_annotation: ^4.5.0
  lottie: ^1.3.0
  location: ^4.2.0
  google_maps_flutter: ^2.1.8
  introduction_screen: ^3.0.2
  flutter_staggered_grid_view: ^0.6.2
  dropdown_search: ^5.0.2
  pdf: ^3.8.3
  open_file: ^3.2.1
  flutter_typeahead: ^4.1.1
  
  timeago: ^3.3.0

  carousel_slider: ^4.1.1
  
  #temp
  analyzer: ^4.1.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  pretty_dio_logger: ^1.1.1
  photo_view: ^0.14.0
  dotted_border: ^2.0.0+2

  expandable_bottom_sheet: ^1.1.1+1


  path: ^1.8.0
  root_package:
    path: ../root_package


  # users presentation
  pinput: ^2.2.9  
  sms_autofill: ^2.2.0
  firebase_messaging: ^14.0.1
  flutter_local_notifications: ^9.9.1
  logger: ^1.1.0
  notification_permissions: ^0.6.1
  universal_platform: ^1.0.0+1
  localstorage: ^4.0.0+1
  badges: ^2.0.3
  animations: ^2.0.5
  easy_debounce: ^2.0.2+1
  expandable: ^5.0.1
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.0.0
  device_preview: ^1.1.0
  responsive_framework: ^0.2.0


  # geo_logic:
  #   path: ../geo_logic
  # geo_presentation:
  #   path: ../geo_presentation 
dev_dependencies:

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4

  flutter_launcher_icons: ^0.10.0
  freezed: ^2.0.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/
    - assets/jsons/
    - assets/vectors/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
       - asset: fonts/Cairo-ExtraLight.ttf
         weight: 200
       - asset: fonts/Cairo-Light.ttf
         weight: 300
       - asset: fonts/Cairo-Regular.ttf
         weight: 400
       - asset: fonts/Cairo-Medium.ttf
         weight: 500
       - asset: fonts/Cairo-SemiBold.ttf
         weight: 600
       - asset: fonts/Cairo-Bold.ttf
         weight: 700
       - asset: fonts/Cairo-ExtraBold.ttf
         weight: 800
       - asset: fonts/Cairo-Black.ttf
         weight: 900
      
   
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n