name: root_package
description: A new Flutter project.
version: 0.0.1

homepage: null

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  bloc: ^8.0.3
  firebase_storage: ^10.2.17
  cloud_firestore: ^3.1.18
  cloud_functions: ^3.2.14
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.16
  firebase_core: ^1.18.0
  firebase_remote_config: ^2.0.9
  firebase_analytics: ^9.1.10
  flow_builder: ^0.0.6
  url_launcher: ^6.1.3

  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.3
  flutter_facebook_auth: ^4.3.0
  flutter_hooks: ^0.18.3
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  form_input: ^0.1.1
  formz: ^0.4.1
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  google_sign_in: ^5.3.2
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  rxdart: ^0.27.3
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.13
  intl_phone_number_input: ^0.7.0+2
  multiple_localization: ^0.3.0
  location: ^4.4.0
  geolocator: ^8.2.1
  permission_handler: ^9.2.0
  app_settings: ^4.1.6
  freezed_annotation: ^2.1.0
  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  injectable_generator: null
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
flutter_intl:
  enabled: false
  class_name: RootPackageLocalizations
  main_locale: en                               # Add this line
  arb_dir: lib/l10n           # Add this line
  output_dir: lib/l10n   # Add this line
  use_deferred_loading: true
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
